### ISSUE TITLE
Installing the library

### ISSUE THREAD

**Issue by anthonywebb** [bitpay/nodejs-bitpay-client#11]
I am getting some error when installing the library and am hoping to understand what is happening and why things are broke.

If I add the library to my project with:
```
npm install bitpay-sdk  --save
```
All appears to install well but when I include the library with, 
```
const bitpaysdk = require('bitpay-sdk');
```
I get the following error:
```
Error: Cannot find module './util/KeyUtils'
```

I suspect it is related to how the library is being built, but I'm short on ideas to get this working on my node 12.14.1 install

**Comment by anbugal** [comment]
Please try installing the latest version (1.3.2102) directly from NPM. Alternatively you can instantiate it by module:
```
const {Client, Env, Currency, Models, Tokens} = require('bitpay-sdk');
